sudo: false
language: node_js
node_js: stable
addons:
  apt:
    packages:
    - xvfb
  firefox: "30.0"
cache:
  apt: true
  directories:
  - node_modules
install:
- npm install
before_script:
- npm run lint
- npm run build
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
script:
- npm test
